In [1]:
import numpy as np

In [2]:
theta = np.array([0.09694976, 0.16223152, 0.06048996, 0.09879951, 0.00459131,
       0.00465799, 0.02550408, 0.01014306, 0.0793229 , 0.14006818,
       0.13161851, 0.0194446 , 0.00573799, 0.13669894, 0.02136491,
       0.00237676])

In [3]:
def calculate_features(sub_features):
    sum = sub_features.sum()
    b = (1/sum)*sub_features
    a = sub_features[0]/b[0]
    return(a , b )

In [4]:
ab1 = theta[0:2]
ab2 = theta[2:6]
ab3 = theta[6:8]
ab4 = theta[8:11]
ab5 = theta[11:13]
ab6 = theta[13:14]
ab7 = theta[14:16]
ab_all = [ab1, ab2, ab3, ab4, ab5, ab6, ab7]
final_a = []
final_b = []
for ab in ab_all:
    a, b = calculate_features(ab)
    final_a.append(a)
    final_b.append(b)
    # print(calculate_features(ab))
final_b[4][-1]= -final_b[4][-1] 
final_a = final_a/np.array(final_a).sum()

In [5]:
print(ab_all)

[array([0.09694976, 0.16223152]), array([0.06048996, 0.09879951, 0.00459131, 0.00465799]), array([0.02550408, 0.01014306]), array([0.0793229 , 0.14006818, 0.13161851]), array([0.0194446 , 0.00573799]), array([0.13669894]), array([0.02136491, 0.00237676])]


In [6]:
def fn_combined_features(features):
    combined = []
    for items in features:
        tmp = []
        for index, item in enumerate(items):
            for _ in item:
                tmp.append(_)
        combined.append(tmp)
    # print(combined)
    return np.array(combined)

In [7]:
def about(value, _min=300, _max=850):
    if value < _min:
        value = _min
    elif value > _max:
        value = _max
    return int(value) 

In [8]:
final_a

array([0.25918129, 0.16853877, 0.03564714, 0.3510096 , 0.02518259,
       0.13669894, 0.02374167])

In [9]:
final_b

[array([0.37406158, 0.62593842]),
 array([0.35890828, 0.58621236, 0.02724186, 0.0276375 ]),
 array([0.71545936, 0.28454064]),
 array([0.22598499, 0.39904374, 0.37497127]),
 array([ 0.77214456, -0.22785544]),
 array([1.]),
 array([0.89989078, 0.10010922])]